In [1]:
import pandas as pd ; import numpy as np; import random as rnd ;import math
#importing data visualization packages
import seaborn as sns ; import matplotlib.pyplot as plt
%matplotlib inline
#importing machine learning packages
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import Imputer
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from IPython.display import display, Math, Latex
import os; import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning)
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings(action='ignore', category=DataConversionWarning)

C:\Users\jmvig\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
mitoclean=pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Statistical-Predictive-Modelling/master/Datasets/mitogroup1.csv")
mitoclean.head(5)

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0  1.442831 -0.686765  0.468785 -0.290551  0.314818 -1.315194  0.243438   
1  1.089354 -0.464034  0.540537 -0.543541 -0.722837  0.890805 -2.843562   
2  1.560937 -0.531389  0.406607 -0.428215  0.380627 -1.441982  0.168146   
3  0.472741 -0.214044 -0.076352  0.473530 -0.276657  0.097556  0.092443   
4  0.962488 -0.039957  0.272991 -0.772692 -0.134409  0.732053 -1.690528   

        PC8       PC9      PC10  ...        PC92      PC93      PC94  \
0 -0.115162  0.218163 -0.115118  ...    0.045520  0.022861 -0.036101   
1  0.941034  0.516424 -0.710239  ...   -0.148358 -0.243735  0.253410   
2 -0.125349  0.272046  0.164182  ...   -0.000791  0.014757 -0.032657   
3  0.242415 -0.276758 -0.184610  ...    0.001585  0.086947 -0.180514   
4  0.341641  0.558391  1.092714  ...   -0.209577 -0.015156  0.041525   

       PC95      PC96      PC97      PC98      PC99     PC100  Group  
0 -0.045053  0.044637  0.032376  0.000209  0.023352  0.052612      3  
1 -0.261774  0.239172  0.169109  0.230727  0.111801 -0.131425      3  
2 -0.005530 -0.010250 -0.078039 -0.041651  0.004365 -0.001871      3  
3  0.126260  0.134495  0.002910 -0.125814 -0.055301  0.014426      3  
4  0.000584  0.056324  0.027536 -0.029483 -0.036062  0.025104      3  

[5 rows x 101 columns]

In [3]:
y_mitogroupclean=pd.DataFrame([mitoclean.Group]).T
x_mitogroupclean=pd.DataFrame(mitoclean)
x_mitogroupclean=mitoclean.drop(['Group'],axis=1)
#print(x_mitogroupclean);print(y_mitogroupclean)
from sklearn.cross_validation import train_test_split
xtrain_mitoclean, xtest_mitoclean, ytrain_mitoclean, ytest_mitoclean=train_test_split(
    x_mitogroupclean,y_mitogroupclean,random_state=1,test_size=0.25)
print(xtrain_mitoclean.shape);print(xtest_mitoclean.shape)
print(ytrain_mitoclean.shape);print(ytest_mitoclean.shape)


(805, 100)
(269, 100)
(805, 1)
(269, 1)


In [4]:
from sklearn.model_selection import cross_val_score
for k in [1,3,4, 5,6, 7,8, 9]:
    knn = KNeighborsClassifier(n_neighbors = k)
    scores = cross_val_score(knn, xtrain_mitoclean, ytrain_mitoclean, cv = 2, scoring = 'accuracy')
    #print(scores)
    print('k: %d. Accuracy: %0.2f +/- %0.2f'%(k, scores.mean(), scores.std()))


k: 1. Accuracy: 1.00 +/- 0.00
k: 3. Accuracy: 1.00 +/- 0.00
k: 4. Accuracy: 1.00 +/- 0.00
k: 5. Accuracy: 1.00 +/- 0.00
k: 6. Accuracy: 1.00 +/- 0.00
k: 7. Accuracy: 1.00 +/- 0.00
k: 8. Accuracy: 1.00 +/- 0.00
k: 9. Accuracy: 0.99 +/- 0.00


In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import confusion_matrix
model = KNeighborsClassifier(n_neighbors = 1) # TESTING FOR K=1 NEIGHBORS
model.fit(xtrain_mitoclean, ytrain_mitoclean)
ymodel_k1 = model.predict(xtest_mitoclean)
acc_knn1 = round(model.score(xtrain_mitoclean, ytrain_mitoclean) * 100, 2)
print ('Training accuracy K=1 = {}'.format(acc_knn1))
acc_knn = round(accuracy_score(ytest_mitoclean, ymodel_k1) * 100, 2)
print ('Testing accuracy K=1= {}'.format(acc_knn))
#RocScore=roc_auc_score(ytest_mitoclean, ymodel_k1) ; RocScore# ROC SCORE FOR K=1 NEIGHBOUR
cm=confusion_matrix(ytest_mitoclean,ymodel_k1)
print(cm)
show_metrics(cm)

Training accuracy K=1 = 100.0
Testing accuracy K=1= 99.63
[[ 16   0   0   0   0   0   0   0]
 [  0  28   0   0   0   0   0   0]
 [  0   0 121   0   0   0   0   0]
 [  0   0   0  21   0   0   0   0]
 [  0   0   0   0  10   0   0   0]
 [  0   0   0   0   0  43   0   0]
 [  0   0   0   0   0   0  10   0]
 [  0   0   0   0   0   1   0  19]]


NameError: name 'show_metrics' is not defined

In [ ]:
model = GaussianNB()  
model.fit(xtrain_mitoclean, ytrain_mitoclean)               
y_model = model.predict(xtest_mitoclean)   
accuracy_score(ytest_mitoclean, y_model)

In [8]:
tree = DecisionTreeClassifier(random_state=0)
tree.fit(xtrain_mitoclean, ytrain_mitoclean)
y_model = tree.predict(xtest_mitoclean)
print("Accuracy on training set: {:.3f}".format(tree.score(xtrain_mitoclean, ytrain_mitoclean)))
print("Accuracy on test set: {:.3f}".format(tree.score(xtest_mitoclean, ytest_mitoclean)))

Accuracy on training set: 1.000
Accuracy on test set: 0.996


In [9]:
svc = SVC(C=1000)
svc.fit(xtrain_mitoclean, ytrain_mitoclean)
print("Accuracy on training set: {:.2f}".format(svc.score(xtrain_mitoclean, ytrain_mitoclean)))
print("Accuracy on test set: {:.2f}".format(svc.score(xtest_mitoclean, ytest_mitoclean)))

Accuracy on training set: 1.00
Accuracy on test set: 1.00
